"""
Pydantic schemas for Planner Agent output validation.
Enforces strict structured JSON format for relevant plans, gatekeeping rejections, and evaluation/re-planning loops.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field, model_validator


class PlannerConstraint(BaseModel):
    """Execution constraint applied to planner/orchestrator tasks."""
    name: str = Field(..., description="Constraint name, e.g. max_delay or max_cycle_split")
    value: str = Field(..., description="Constraint threshold value")
    unit: str = Field(..., description="Unit of measurement, e.g. seconds or vehicles/hr")


class OrchestratorExecuteRequest(BaseModel):
    """
    Standard request payload generated by the Planner Agent when dispatching an orchestrator workflow.
    """
    request_id: str = Field(..., description="Unique request identifier")
    workflow: str = Field(default="monitor-detect-understand", description="Workflow name")
    steps: List[str] = Field(default_factory=list, description="Ordered execution steps")
    priority: int = Field(default=3, ge=1, le=5, description="Priority level 1-5")
    objective: Optional[str] = Field(default=None, description="Planner objective in natural language")
    location: Optional[str] = Field(default=None, description="Target location or corridor")
    domains: List[str] = Field(default_factory=lambda: ["traffic"], description="List of involved domains")
    constraints: List[PlannerConstraint] = Field(default_factory=list, description="List of execution constraints")


class PlannerResponse(BaseModel):
    """
    Structured output schema for the Planner Agent conforming to the Task Execution JSON standard.
    """
    task_id: str = Field(
        ...,
        description="Unique ID for the created planning task."
    )
    request_id: str = Field(
        ...,
        description="Unique request identifier."
    )
    status: Literal["QUEUED", "IN_PROGRESS", "COMPLETED", "FAILED", "REJECTED"] = Field(
        default="QUEUED",
        description="Current status of the planning task."
    )
    assigned_capabilities: List[str] = Field(
        default_factory=list,
        description="Capabilities assigned by the planner to address the request."
    )
    dispatched_agents: List[str] = Field(
        default_factory=list,
        description="Specialist agents dispatched to perform the plan steps."
    )
    collected_results: Dict[str, Any] = Field(
        default_factory=dict,
        description="Collected execution results from specialist agents."
    )
    failures: Dict[str, Any] = Field(
        default_factory=dict,
        description="Failures or errors encountered during step execution."
    )
    planner_feedback: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Feedback, reasoning, objective, and domain gatekeeping details from the planner."
    )
    created_at: str = Field(
        ...,
        description="ISO 8601 timestamp string when the task was created."
    )

    @property
    def relevant(self) -> bool:
        if self.planner_feedback and isinstance(self.planner_feedback, dict):
            return self.planner_feedback.get("relevant", self.status != "REJECTED")
        return self.status != "REJECTED"

    @property
    def domain(self) -> Optional[str]:
        if self.planner_feedback and isinstance(self.planner_feedback, dict):
            return self.planner_feedback.get("domain")
        return None

    @property
    def objective(self) -> Optional[str]:
        if self.planner_feedback and isinstance(self.planner_feedback, dict):
            return self.planner_feedback.get("objective")
        return None

    @property
    def plan(self) -> List[str]:
        if self.planner_feedback and isinstance(self.planner_feedback, dict):
            return self.planner_feedback.get("plan", [])
        return []

    @property
    def response(self) -> Optional[str]:
        if self.planner_feedback and isinstance(self.planner_feedback, dict):
            return self.planner_feedback.get("response")
        return None


class PlannerEvaluationResponse(BaseModel):
    """
    Structured output schema for the Planner Agent's result evaluation and re-planning step.
    """
    goal_achieved: bool = Field(
        ...,
        description="Whether the collected specialist agent data and simulation results satisfy the planning objective."
    )
    decision: Literal["PROCEED_TO_RECOMMENDATION", "RE_PLAN", "ABORT"] = Field(
        ...,
        description="Next strategic decision: proceed to final recommendation, trigger re-planning, or abort."
    )
    analysis: str = Field(
        ...,
        description="Strategic analysis explaining how the returned data addresses the bottleneck, delays, or traffic conditions."
    )
    final_recommendation: Optional[str] = Field(
        default=None,
        description="Actionable policy or signal recommendation for municipal planners if goal is achieved."
    )
    revised_plan: List[str] = Field(
        default_factory=list,
        description="Ordered list of revised execution steps if the goal was not achieved and re-planning is required."
    )
    confidence: float = Field(
        default=0.90,
        ge=0.0,
        le=1.0,
        description="Planner confidence score in this evaluation."
    )


# Alias matching supervisor contract
OrchestratorExecuteResponse = PlannerResponse

