"""
Pydantic schemas for Planner Agent output validation and LLM structured responses.
Enforces strict structured JSON format for relevant plans, gatekeeping rejections,
LLM agent selections, multi-cycle evaluations, and final cross-agent synthesis.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field, model_validator


class SeverityLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EvidenceItem(BaseModel):
    """
    Structured evidence model representing atomic telemetry or insight from a specialist agent.
    Preserves metric names, values, units, timestamps, locations, and severities.
    """
    source: str = Field(..., description="Source agent, e.g. traffic, weather, pollution, energy, simulation")
    metric: str = Field(..., description="Metric key, e.g. congestion_index, precipitation_mm, avg_speed_kmh, aqi, load_pct")
    value: Any = Field(..., description="Measured or modeled value")
    unit: Optional[str] = Field(default=None, description="Physical unit, e.g. %, km/h, mm, ug/m3, MW")
    location: Optional[str] = Field(default=None, description="Spatial context or corridor/junction name")
    severity: SeverityLevel = Field(default=SeverityLevel.LOW, description="Assessed severity level")
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    details: Dict[str, Any] = Field(default_factory=dict, description="Supplementary contextual data or sub-metrics")
    timestamp: Optional[str] = Field(default=None)


class CrossDomainAnalysis(BaseModel):
    """
    Cross-domain synthesized insights across multiple specialist agents.
    """
    primary_correlation: str = Field(..., description="E.g. 'Weather -> Traffic delay compounding'")
    risk_level: SeverityLevel = Field(default=SeverityLevel.MODERATE)
    speed_impact_pct: Optional[float] = Field(default=None, description="Estimated or simulated percentage change in speed")
    causation_likelihood: str = Field(default="PLAUSIBLE", description="PLAUSIBLE, STRONG, UNLIKELY, INDEPENDENT")
    key_findings: List[str] = Field(default_factory=list)
    diagnosed_bottlenecks: List[str] = Field(default_factory=list)
    candidate_interventions: List[str] = Field(default_factory=list)
    simulation_comparison: Optional[Dict[str, Any]] = Field(default=None, description="Baseline vs simulated intervention comparison")


class ScenarioDefinition(BaseModel):
    scenario_id: str
    label: str
    assumptions: List[str] = Field(default_factory=list)
    intervention: Optional[str] = None


class AgentContextRequest(BaseModel):
    """
    Contract-aware input context built by Planner for a specialist agent.
    """
    capability: str
    target_endpoint: str
    method: str = "GET"
    location: str
    payload: Dict[str, Any] = Field(default_factory=dict)
    required_fields: List[str] = Field(default_factory=list)
    missing_fields: List[str] = Field(default_factory=list)
    is_complete: bool = True


class AgentRequest(BaseModel):
    """
    Structured specialist agent request generated by the LLM Planner.
    Adheres to the machine-readable contract for the agent.
    """
    agent: str = Field(..., description="Target specialist capability: 'traffic', 'weather', 'pollution', 'energy', or 'simulation'")
    request: Dict[str, Any] = Field(default_factory=dict, description="Agent-specific input payload generated by the LLM based on the agent's contract")
    reason: Optional[str] = Field(default=None, description="LLM justification for why this specialist agent is required")

    @model_validator(mode="before")
    @classmethod
    def sync_request_input(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "input" in data and "request" not in data:
                data["request"] = data["input"]
            elif "request" in data and "input" not in data:
                data["input"] = data["request"]
            elif "generated_inputs" in data and "request" not in data:
                data["request"] = data["generated_inputs"]
                data["input"] = data["generated_inputs"]
        return data

    @property
    def input(self) -> Dict[str, Any]:
        return self.request


# Backward compatibility alias
SelectedAgentCall = AgentRequest


class LLMPlanDecision(BaseModel):
    """
    Structured output schema for the LLM Planner's autonomous initial planning cycle.
    Contains strictly the understanding, selected agents with contract payloads, and next action.
    Does NOT mix in speculative causes or simulation scenarios before specialist evidence exists.
    """
    relevant: bool = Field(..., description="Whether the user query is relevant to the Smart City domain.")
    request_id: Optional[str] = Field(default=None)
    objective: Optional[str] = Field(default=None, description="Extracted planner objective.")
    objective_understanding: Optional[str] = Field(default=None, description="LLM's understanding of the user's objective in natural language.")
    identified_problem: Optional[str] = Field(default=None, description="The primary urban challenge identified from the objective.")
    required_capabilities: List[str] = Field(default_factory=list, description="Capabilities required for this initial cycle.")
    agent_requests: List[AgentRequest] = Field(default_factory=list, description="Specialist agents selected by the LLM with generated contract-adherent inputs.")
    next_action: str = Field(default="collect_evidence", description="collect_evidence, run_simulation, or finalize")
    cycle: int = Field(default=1)
    scenarios: Optional[List[Dict[str, Any]]] = Field(default=None, description="Simulation scenarios only if explicitly required by the objective.")
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Optional confidence score; must not be fabricated.")
    response: Optional[str] = Field(default=None, description="Explanation message if the query is rejected or out of scope.")

    @model_validator(mode="before")
    @classmethod
    def sync_agents_and_normalize(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "selected_agents" in data and "agent_requests" not in data:
                data["agent_requests"] = data["selected_agents"]
            elif "agent_requests" in data and "selected_agents" not in data:
                data["selected_agents"] = data["agent_requests"]
            if not data.get("required_capabilities") and data.get("agent_requests"):
                caps = []
                for req in data["agent_requests"]:
                    if isinstance(req, dict) and "agent" in req and req["agent"] not in caps:
                        caps.append(req["agent"])
                    elif hasattr(req, "agent") and req.agent not in caps:
                        caps.append(req.agent)
                data["required_capabilities"] = caps
            if not data.get("objective") and data.get("objective_understanding"):
                data["objective"] = data["objective_understanding"]

            # Defensive next_action normalization and state-aware fallback
            raw_action = data.get("next_action")
            action_str = str(raw_action).strip().lower() if raw_action is not None else ""

            # Check relevance
            is_relevant = data.get("relevant", True)
            if isinstance(is_relevant, str):
                is_relevant = is_relevant.lower() not in ("false", "0", "no")

            # Extract requested capability names
            req_caps = [str(c).lower().strip() for c in (data.get("required_capabilities") or [])]
            agent_reqs = data.get("agent_requests") or []
            agent_names = []
            for ar in agent_reqs:
                if isinstance(ar, dict) and "agent" in ar:
                    agent_names.append(str(ar["agent"]).lower().strip())
                elif hasattr(ar, "agent"):
                    agent_names.append(str(ar.agent).lower().strip())
            all_requested = req_caps + agent_names

            has_simulation = "simulation" in all_requested
            has_specialist = any(c in ("traffic", "weather", "pollution", "energy") for c in all_requested)

            # Map recognized aliases
            if action_str in ("collect_evidence", "collect", "gather_evidence", "collect-evidence"):
                data["next_action"] = "collect_evidence"
            elif action_str in ("run_simulation", "simulate", "simulation", "run-simulation"):
                data["next_action"] = "run_simulation"
            elif action_str in ("finalize", "complete", "done", "finish", "proceed_to_recommendation", "answer_immediately"):
                data["next_action"] = "finalize"
            elif action_str in ("abort", "error", "fail", "cancel"):
                data["next_action"] = "abort"
            elif action_str in ("request_more_evidence", "need_more_evidence"):
                data["next_action"] = "request_more_evidence"
            else:
                # Semantic state-aware fallback when next_action is null, empty string, or unrecognized:
                if not is_relevant:
                    data["next_action"] = "finalize"
                elif has_simulation:
                    data["next_action"] = "run_simulation"
                elif has_specialist:
                    data["next_action"] = "collect_evidence"
                else:
                    # No specialist agents requested (immediate answer, clarifying prompt, or out-of-scope)
                    data["next_action"] = "finalize"
        return data

    @property
    def selected_agents(self) -> List[AgentRequest]:
        return self.agent_requests


class LLMEvaluationDecision(BaseModel):
    """
    Structured output schema for the LLM Planner's evidence sufficiency and replanning evaluation.
    """
    evidence_sufficient: bool = Field(..., description="Whether collected evidence is sufficient to answer the objective.")
    decision: str = Field(
        ...,
        description="Next strategic decision determined by the LLM: finalize, request_more_evidence, run_simulation, abort."
    )
    next_action: str = Field(
        default="finalize",
        description="Dynamic next action: finalize, request_more_evidence, run_simulation, abort."
    )
    analysis: str = Field(..., description="LLM's strategic analysis of the evidence and findings so far.")
    missing_information: List[str] = Field(default_factory=list, description="Information still missing if evidence is not sufficient.")
    agent_requests: List[AgentRequest] = Field(default_factory=list, description="Additional specialist agents requested for the next cycle.")
    required_capabilities: List[str] = Field(default_factory=list, description="Capabilities requested for next cycle.")
    simulation_context: Optional[Dict[str, Any]] = Field(default=None, description="Specific parameters for simulation if simulation is required.")
    scenarios: Optional[List[Dict[str, Any]]] = Field(default=None, description="Intervention experiment scenarios if simulation is needed.")
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Optional confidence score; must not be fabricated.")

    @model_validator(mode="before")
    @classmethod
    def normalize_decision_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "next_agents" in data and "agent_requests" not in data:
                data["agent_requests"] = data["next_agents"]
            elif "agent_requests" in data and "next_agents" not in data:
                data["next_agents"] = data["agent_requests"]

            dec = str(data.get("decision", "")).strip().lower()
            # Normalize decision
            if dec in ("proceed_to_recommendation", "enough_evidence", "finalize"):
                data["decision"] = "finalize"
            elif dec in ("request_additional_agent", "need_more_evidence", "request_more_evidence"):
                data["decision"] = "request_more_evidence"
            elif dec in ("run_simulation", "simulate", "simulation"):
                data["decision"] = "run_simulation"
            elif dec in ("abort", "cancel", "error", "fail"):
                data["decision"] = "abort"
            elif not dec:
                data["decision"] = "finalize"

            # Normalize next_action (handle null, empty, or aliased)
            raw_action = data.get("next_action")
            action_str = str(raw_action).strip().lower() if raw_action is not None else ""
            if action_str in ("finalize", "proceed_to_recommendation", "done"):
                data["next_action"] = "finalize"
            elif action_str in ("request_more_evidence", "need_more_evidence"):
                data["next_action"] = "request_more_evidence"
            elif action_str in ("run_simulation", "simulate"):
                data["next_action"] = "run_simulation"
            elif action_str in ("abort", "fail", "cancel"):
                data["next_action"] = "abort"
            else:
                data["next_action"] = data["decision"]

            if not data.get("required_capabilities") and data.get("agent_requests"):
                caps = []
                for req in data["agent_requests"]:
                    if isinstance(req, dict) and "agent" in req and req["agent"] not in caps:
                        caps.append(req["agent"])
                    elif hasattr(req, "agent") and req.agent not in caps:
                        caps.append(req.agent)
                data["required_capabilities"] = caps
        return data

    @property
    def next_agents(self) -> List[AgentRequest]:
        return self.agent_requests


class ResponseScope(BaseModel):
    """
    Structured response scope determining requested fields and detail level.
    Determined from the user's natural language request by the LLM Planner.
    """
    fields: List[str] = Field(
        default_factory=list,
        description="Fields or topics explicitly requested by the user, e.g. ['bottleneck_corridor'], ['average_speed'], ['causes'], ['recommendations']."
    )
    detail_level: Literal["minimal", "summary", "analysis", "full"] = Field(
        default="minimal",
        description="Level of detail requested: 'minimal' for direct answers to narrow queries, 'summary' for brief overviews, 'analysis' for in-depth evaluations."
    )


class LLMFinalReasoning(BaseModel):
    """
    Structured output schema for the LLM Planner's final cross-agent synthesis.
    Separated from intermediate planning state.
    """
    summary: str = Field(..., description="Comprehensive overview explaining what happened across domains.")
    evidence_used: List[str] = Field(default_factory=list, description="Specific metrics cited from actual agent telemetry.")
    cross_domain_relationships: str = Field(..., description="Explanation of interactions between domains (e.g. weather and traffic friction).")
    causation_likelihood: Literal["STRONG", "PLAUSIBLE", "UNLIKELY", "INDEPENDENT"] = Field(
        default="PLAUSIBLE",
        description="Scientific assessment of whether correlation represents direct causation or coincidence."
    )
    simulation_findings: Optional[str] = Field(default=None, description="Interpretation of SUMO simulation metrics if simulation was executed.")
    synthetic_data_note: Optional[str] = Field(
        default="SUMO simulation metrics represent simulated/synthetic evidence under a defined traffic-demand scenario, distinct from live physical road sensors.",
        description="Notice regarding the synthetic nature of SUMO simulation results."
    )
    uncertainty_and_limitations: str = Field(..., description="Noted limitations, data gaps, or sensor assumptions.")
    recommendation: str = Field(default="", description="Actionable municipal policy, routing, or signal recommendation.")
    response_scope: Optional[ResponseScope] = Field(default=None, description="Structured scope determined from user request specifying requested fields and detail level.")
    requested_scope: Optional[List[str]] = Field(default=None, description="List of requested field names for backward compatibility.")
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Optional confidence score; must not be fabricated.")
    next_action: str = Field(default="operational_implementation", description="Immediate operational next step for municipal operations.")
    evidence_status: str = Field(
        default="EVIDENCE: OBSERVATIONAL",
        description="Evidence status: EVIDENCE: OBSERVATIONAL | EVIDENCE: SINGLE SIMULATION RUN | EVIDENCE: MULTI-SIMULATION EVALUATION"
    )
    tested_interventions: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="List of candidate interventions actually executed in SUMO microsimulation with empirical evidence in this cycle."
    )
    untested_candidates: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="Candidate interventions identified from specialist intelligence that were NOT executed or simulated in this cycle."
    )
    recommendation_basis: Optional[str] = Field(
        default=None,
        description="Structured rationale for the recommendation, strictly distinguishing between tested and untested interventions."
    )
    baseline_metrics: Optional[Dict[str, Any]] = Field(default=None, description="Baseline empirical metrics prior to intervention.")
    diagnosed_bottlenecks: Optional[List[str]] = Field(default=None, description="Observed bottlenecks using speed-based diagnostics.")
    intervention: Optional[Dict[str, Any]] = Field(default=None, description="Candidate intervention evaluated in simulation.")
    intervention_metrics: Optional[Dict[str, Any]] = Field(default=None, description="Intervention empirical simulation metrics.")
    metric_changes: Optional[Dict[str, Any]] = Field(default=None, description="Calculated percentage and absolute deltas between baseline and intervention.")
    intervention_assessment: Optional[str] = Field(default=None, description="Semantic evaluation of whether the intervention successfully improves target bottleneck.")
    key_findings: Optional[List[str]] = Field(default=None, description="Key empirical findings from specialist telemetry.")
    tested_scenarios: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="All evaluated simulation scenarios with intervention parameters, empirical metrics, corridor trade-offs, and baseline comparisons."
    )
    corridor_trade_offs: Optional[List[str]] = Field(
        default_factory=list,
        description="Identified trade-offs on other corridors resulting from candidate interventions."
    )
    selected_scenario_id: Optional[str] = Field(
        default=None,
        description="Deterministic ID of preferred or recommended scenario based on balanced evaluation."
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_final_reasoning(cls, data: Any) -> Any:
        if isinstance(data, dict):
            raw_action = data.get("next_action")
            if not raw_action or str(raw_action).strip().lower() in ("null", "none"):
                data["next_action"] = "operational_implementation"
            else:
                data["next_action"] = str(raw_action).strip()
        return data

    @property
    def requested_scope(self) -> List[str]:
        if self.response_scope and self.response_scope.fields:
            return self.response_scope.fields
        return []




class PlannerResponse(BaseModel):
    """
    Structured output schema for the Planner Agent's initial plan generation and gatekeeping.
    Maintained for public API compatibility.
    """
    relevant: bool = Field(..., description="Whether the user query is relevant to the Smart City domain.")
    domain: Optional[str] = Field(default=None, description="Primary domain of the query.")
    objective: Optional[str] = Field(default=None, description="Concise, extracted planner objective.")
    plan: List[str] = Field(default_factory=list, description="Ordered list of execution steps.")
    response: Optional[str] = Field(default=None, description="Explanation when query is rejected.")
    selected_agents: List[AgentRequest] = Field(default_factory=list, description="Specialist agents selected by LLM.")
    required_capabilities: List[str] = Field(default_factory=list)
    next_action: str = Field(default="collect_evidence")

    @model_validator(mode="after")
    def validate_gatekeeping_consistency(self) -> PlannerResponse:
        if self.relevant:
            if not self.domain and self.selected_agents:
                self.domain = self.selected_agents[0].agent
            elif not self.domain:
                self.domain = "traffic"
            if not self.objective or not self.objective.strip():
                raise ValueError("Relevant query must specify an 'objective'.")
            if not self.required_capabilities and self.selected_agents:
                self.required_capabilities = [sa.agent for sa in self.selected_agents]
            self.response = None
        else:
            self.domain = None
            self.objective = None
            self.plan = []
            self.selected_agents = []
            self.required_capabilities = []
            if not self.response or not self.response.strip():
                self.response = "This question is outside the scope of the Smart City system."
        return self


class PlannerEvaluationResponse(BaseModel):
    """
    Structured output schema for the Planner Agent's result evaluation and re-planning step.
    Maintained for supervisor loop compatibility.
    """
    goal_achieved: bool = Field(..., description="Whether the collected data satisfies the objective.")
    decision: str = Field(..., description="Next strategic decision: finalize, request_more_evidence, run_simulation, abort.")
    next_action: str = Field(default="finalize", description="Next operational action.")
    analysis: str = Field(..., description="Strategic analysis.")
    final_recommendation: Optional[str] = Field(default=None, description="Actionable recommendation.")
    final_reasoning: Optional[LLMFinalReasoning] = Field(default=None, description="Comprehensive final reasoning synthesis if finalized.")
    revised_plan: List[str] = Field(default_factory=list, description="Revised steps if re-planning.")
    evidence_status: str = Field(
        default="EVIDENCE: OBSERVATIONAL",
        description="Evidence status: EVIDENCE: OBSERVATIONAL | EVIDENCE: SINGLE SIMULATION RUN | EVIDENCE: MULTI-SIMULATION EVALUATION"
    )
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    evidence: List[EvidenceItem] = Field(default_factory=list, description="Structured atomic evidence.")
    cross_analysis: Optional[CrossDomainAnalysis] = Field(default=None, description="Cross-domain reasoning results.")
    next_cycle_caps: List[str] = Field(default_factory=list, description="Capabilities requested for next cycle.")
    next_cycle_calls: List[AgentRequest] = Field(default_factory=list, description="Detailed agent calls for next cycle.")
    simulation_context: Optional[Dict[str, Any]] = Field(default=None, description="Derived scenario parameters for simulation.")
    scenarios: Optional[List[Dict[str, Any]]] = Field(default=None, description="Experimental scenarios if simulation is needed.")
    response_scope: Optional[ResponseScope] = Field(default=None, description="Structured response scope specifying requested fields and detail level.")
    requested_scope: Optional[List[str]] = Field(default=None, description="List of requested field names for backward compatibility.")

    @model_validator(mode="after")
    def sync_requested_scope(self) -> PlannerEvaluationResponse:
        if self.requested_scope is None:
            if self.response_scope and self.response_scope.fields:
                self.requested_scope = self.response_scope.fields
            elif self.final_reasoning and self.final_reasoning.response_scope:
                self.requested_scope = self.final_reasoning.response_scope.fields
            else:
                self.requested_scope = []
        return self

    @property
    def tested_interventions(self) -> List[Dict[str, Any]]:
        return self.final_reasoning.tested_interventions if self.final_reasoning else []

    @property
    def untested_candidates(self) -> List[Dict[str, Any]]:
        return self.final_reasoning.untested_candidates if self.final_reasoning else []
